package com.alten.shop.config;

import com.alten.shop.model.InventoryStatus;
import com.alten.shop.model.Product;
import com.alten.shop.model.User;
import com.alten.shop.repository.ProductRepository;
import com.alten.shop.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;

@Component
@RequiredArgsConstructor
public class DataInitializer implements CommandLineRunner {

    private final ProductRepository productRepository;
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    public void run(String... args) {
        // Create admin user
        if (!userRepository.existsByEmail("hosnibey@admin.com")) {
            User admin = User.builder()
                    .username("hosnibey")
                    .firstname("Hosni")
                    .email("hosnibey@admin.com")
                    .password(passwordEncoder.encode("hosnibey"))
                    .build();
            userRepository.save(admin);
            System.out.println("Admin user created: hosnibey@admin.com / hosnibey");
        }

        System.out.println("Initializing database with sample products...");

        List<Product> products = Arrays.asList(
                Product.builder()
                        .code("LAPTOP001")
                        .name("Dell XPS 15")
                        .description("High-performance laptop with 15.6-inch display, Intel i7, 16GB RAM")
                        .image("https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400")
                        .category("Electronics")
                        .price(1299.99)
                        .quantity(15)
                        .internalReference("DELL-XPS-15-2024")
                        .shellId(1L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.7)
                        .build(),

                Product.builder()
                        .code("PHONE001")
                        .name("iPhone 15 Pro")
                        .description("Latest iPhone with A17 Pro chip, titanium design, 256GB storage")
                        .image("https://images.unsplash.com/photo-1592286927505-38c8f877d0f0?w=400")
                        .category("Electronics")
                        .price(999.99)
                        .quantity(25)
                        .internalReference("APPLE-IP15P-256")
                        .shellId(2L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.9)
                        .build(),

                Product.builder()
                        .code("HEADPHONE001")
                        .name("Sony WH-1000XM5")
                        .description("Premium noise-canceling wireless headphones")
                        .image("https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400")
                        .category("Electronics")
                        .price(399.99)
                        .quantity(8)
                        .internalReference("SONY-WH1000XM5")
                        .shellId(3L)
                        .inventoryStatus(InventoryStatus.LOWSTOCK)
                        .rating(4.8)
                        .build(),

                Product.builder()
                        .code("TABLET001")
                        .name("iPad Pro 12.9\"")
                        .description("Powerful tablet with M2 chip, 12.9-inch Liquid Retina display")
                        .image("https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400")
                        .category("Electronics")
                        .price(1099.99)
                        .quantity(12)
                        .internalReference("APPLE-IPADPRO-129")
                        .shellId(4L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.6)
                        .build(),

                Product.builder()
                        .code("WATCH001")
                        .name("Apple Watch Series 9")
                        .description("Advanced health and fitness smartwatch")
                        .image("https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400")
                        .category("Electronics")
                        .price(429.99)
                        .quantity(20)
                        .internalReference("APPLE-WATCH-S9")
                        .shellId(5L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.5)
                        .build(),

                Product.builder()
                        .code("CAMERA001")
                        .name("Canon EOS R6")
                        .description("Professional mirrorless camera with 20.1MP sensor")
                        .image("https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400")
                        .category("Electronics")
                        .price(2499.99)
                        .quantity(5)
                        .internalReference("CANON-EOSR6")
                        .shellId(6L)
                        .inventoryStatus(InventoryStatus.LOWSTOCK)
                        .rating(4.9)
                        .build(),

                Product.builder()
                        .code("KEYBOARD001")
                        .name("Logitech MX Keys")
                        .description("Advanced wireless illuminated keyboard")
                        .image("https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400")
                        .category("Accessories")
                        .price(99.99)
                        .quantity(30)
                        .internalReference("LOGI-MXKEYS")
                        .shellId(7L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.4)
                        .build(),

                Product.builder()
                        .code("MOUSE001")
                        .name("Logitech MX Master 3S")
                        .description("Advanced wireless mouse with precision scrolling")
                        .image("https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400")
                        .category("Accessories")
                        .price(99.99)
                        .quantity(35)
                        .internalReference("LOGI-MXMASTER3S")
                        .shellId(8L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.7)
                        .build(),

                Product.builder()
                        .code("MONITOR001")
                        .name("LG UltraWide 34\"")
                        .description("34-inch curved ultrawide monitor, 3440x1440 resolution")
                        .image("https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400")
                        .category("Electronics")
                        .price(699.99)
                        .quantity(10)
                        .internalReference("LG-UW34")
                        .shellId(9L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.6)
                        .build(),

                Product.builder()
                        .code("SPEAKER001")
                        .name("Bose SoundLink Revolve+")
                        .description("Portable Bluetooth speaker with 360-degree sound")
                        .image("https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400")
                        .category("Electronics")
                        .price(299.99)
                        .quantity(0)
                        .internalReference("BOSE-SLRP")
                        .shellId(10L)
                        .inventoryStatus(InventoryStatus.OUTOFSTOCK)
                        .rating(4.5)
                        .build(),

                Product.builder()
                        .code("CHARGER001")
                        .name("Anker PowerPort III")
                        .description("65W USB-C fast charger with GaN technology")
                        .image("https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400")
                        .category("Accessories")
                        .price(49.99)
                        .quantity(50)
                        .internalReference("ANKER-PP3-65W")
                        .shellId(11L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.3)
                        .build(),

                Product.builder()
                        .code("CABLE001")
                        .name("USB-C to USB-C Cable")
                        .description("Braided 2m USB-C cable, 100W power delivery")
                        .image("https://images.unsplash.com/photo-1591290619762-d71b2e2a4c14?w=400")
                        .category("Accessories")
                        .price(19.99)
                        .quantity(100)
                        .internalReference("CABLE-USBC-2M")
                        .shellId(12L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.2)
                        .build(),

                // Additional 30 products for pagination testing
                Product.builder()
                        .code("LAPTOP002")
                        .name("MacBook Pro 16\"")
                        .description("Powerful laptop with M3 Pro chip, 512GB SSD")
                        .image("https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400")
                        .category("Electronics")
                        .price(1999.99)
                        .quantity(8)
                        .internalReference("APPLE-MBP16-M3")
                        .shellId(13L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.8)
                        .build(),

                Product.builder()
                        .code("LAPTOP003")
                        .name("HP Pavilion 15")
                        .description("Budget-friendly laptop with Intel i5, 8GB RAM")
                        .image("https://images.unsplash.com/photo-1588405349956-e491cc2a30d7?w=400")
                        .category("Electronics")
                        .price(599.99)
                        .quantity(18)
                        .internalReference("HP-PAV15-I5")
                        .shellId(14L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.2)
                        .build(),

                Product.builder()
                        .code("PHONE002")
                        .name("Samsung Galaxy S24")
                        .description("Flagship Android phone with 50MP camera")
                        .image("https://images.unsplash.com/photo-1511707267537-b85faf00021e?w=400")
                        .category("Electronics")
                        .price(899.99)
                        .quantity(22)
                        .internalReference("SAMSUNG-S24")
                        .shellId(15L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.7)
                        .build(),

                Product.builder()
                        .code("PHONE003")
                        .name("Google Pixel 8")
                        .description("Google's flagship with advanced AI features")
                        .image("https://images.unsplash.com/photo-1520923961943-e292105264bb?w=400")
                        .category("Electronics")
                        .price(799.99)
                        .quantity(16)
                        .internalReference("GOOGLE-PIXEL8")
                        .shellId(16L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.6)
                        .build(),

                Product.builder()
                        .code("HEADPHONE002")
                        .name("Bose QuietComfort 45")
                        .description("Premium noise-canceling headphones")
                        .image("https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400")
                        .category("Electronics")
                        .price(349.99)
                        .quantity(14)
                        .internalReference("BOSE-QC45")
                        .shellId(17L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.7)
                        .build(),

                Product.builder()
                        .code("HEADPHONE003")
                        .name("JBL Tune 750")
                        .description("Wireless over-ear headphones with long battery")
                        .image("https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400")
                        .category("Electronics")
                        .price(149.99)
                        .quantity(28)
                        .internalReference("JBL-TUNE750")
                        .shellId(18L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.3)
                        .build(),

                Product.builder()
                        .code("TABLET002")
                        .name("Samsung Galaxy Tab S9")
                        .description("Android tablet with AMOLED display")
                        .image("https://images.unsplash.com/photo-1561504219-84f161eba84f?w=400")
                        .category("Electronics")
                        .price(799.99)
                        .quantity(11)
                        .internalReference("SAMSUNG-TAB-S9")
                        .shellId(19L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.5)
                        .build(),

                Product.builder()
                        .code("TABLET003")
                        .name("Microsoft Surface Pro 9")
                        .description("2-in-1 tablet with detachable keyboard")
                        .image("https://images.unsplash.com/photo-1568043666747-39d8f1556e55?w=400")
                        .category("Electronics")
                        .price(949.99)
                        .quantity(7)
                        .internalReference("MSFT-SP9")
                        .shellId(20L)
                        .inventoryStatus(InventoryStatus.LOWSTOCK)
                        .rating(4.6)
                        .build(),

                Product.builder()
                        .code("WATCH002")
                        .name("Samsung Galaxy Watch 6")
                        .description("Android smartwatch with AMOLED display")
                        .image("https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400")
                        .category("Electronics")
                        .price(299.99)
                        .quantity(19)
                        .internalReference("SAMSUNG-WATCH6")
                        .shellId(21L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.5)
                        .build(),

                Product.builder()
                        .code("WATCH003")
                        .name("Garmin Forerunner 965")
                        .description("Advanced sports smartwatch with GPS")
                        .image("https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400")
                        .category("Electronics")
                        .price(599.99)
                        .quantity(6)
                        .internalReference("GARMIN-FR965")
                        .shellId(22L)
                        .inventoryStatus(InventoryStatus.LOWSTOCK)
                        .rating(4.8)
                        .build(),

                Product.builder()
                        .code("CAMERA002")
                        .name("Sony A7R V")
                        .description("High-resolution mirrorless camera 61MP")
                        .image("https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=400")
                        .category("Electronics")
                        .price(3498.00)
                        .quantity(3)
                        .internalReference("SONY-A7RV")
                        .shellId(23L)
                        .inventoryStatus(InventoryStatus.LOWSTOCK)
                        .rating(4.9)
                        .build(),

                Product.builder()
                        .code("CAMERA003")
                        .name("Nikon Z9")
                        .description("Professional flagship mirrorless camera")
                        .image("https://images.unsplash.com/photo-1609034227505-5876f6aa4e90?w=400")
                        .category("Electronics")
                        .price(5496.95)
                        .quantity(2)
                        .internalReference("NIKON-Z9")
                        .shellId(24L)
                        .inventoryStatus(InventoryStatus.LOWSTOCK)
                        .rating(4.9)
                        .build(),

                Product.builder()
                        .code("MONITOR002")
                        .name("Dell UltraSharp U2723DE")
                        .description("27-inch 4K IPS monitor for professionals")
                        .image("https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400")
                        .category("Electronics")
                        .price(799.99)
                        .quantity(9)
                        .internalReference("DELL-U2723DE")
                        .shellId(25L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.7)
                        .build(),

                Product.builder()
                        .code("MONITOR003")
                        .name("ASUS ProArt PA248QV")
                        .description("24-inch color-accurate monitor")
                        .image("https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400")
                        .category("Electronics")
                        .price(549.99)
                        .quantity(13)
                        .internalReference("ASUS-PA248QV")
                        .shellId(26L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.6)
                        .build(),

                Product.builder()
                        .code("KEYBOARD002")
                        .name("Corsair K95 Platinum")
                        .description("Mechanical gaming keyboard with RGB lighting")
                        .image("https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400")
                        .category("Accessories")
                        .price(229.99)
                        .quantity(12)
                        .internalReference("CORSAIR-K95P")
                        .shellId(27L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.6)
                        .build(),

                Product.builder()
                        .code("KEYBOARD003")
                        .name("Keychron Q1 Pro")
                        .description("Wireless mechanical keyboard")
                        .image("https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400")
                        .category("Accessories")
                        .price(189.99)
                        .quantity(24)
                        .internalReference("KEYCHRON-Q1P")
                        .shellId(28L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.5)
                        .build(),

                Product.builder()
                        .code("MOUSE002")
                        .name("Razer DeathAdder V3")
                        .description("Gaming mouse with 30000 DPI sensor")
                        .image("https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400")
                        .category("Accessories")
                        .price(69.99)
                        .quantity(32)
                        .internalReference("RAZER-DA-V3")
                        .shellId(29L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.7)
                        .build(),

                Product.builder()
                        .code("MOUSE003")
                        .name("SteelSeries Prime Wireless")
                        .description("Esports-grade wireless gaming mouse")
                        .image("https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400")
                        .category("Accessories")
                        .price(79.99)
                        .quantity(27)
                        .internalReference("STEELSERIES-PW")
                        .shellId(30L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.6)
                        .build(),

                Product.builder()
                        .code("SPEAKER002")
                        .name("JBL PartyBox 310")
                        .description("Powerful portable party speaker with lights")
                        .image("https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400")
                        .category("Electronics")
                        .price(599.99)
                        .quantity(5)
                        .internalReference("JBL-PB310")
                        .shellId(31L)
                        .inventoryStatus(InventoryStatus.LOWSTOCK)
                        .rating(4.6)
                        .build(),

                Product.builder()
                        .code("SPEAKER003")
                        .name("Marshall Stanmore II")
                        .description("Classic design Bluetooth speaker")
                        .image("https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400")
                        .category("Electronics")
                        .price(399.99)
                        .quantity(11)
                        .internalReference("MARSHALL-S2")
                        .shellId(32L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.5)
                        .build(),

                Product.builder()
                        .code("CHARGER002")
                        .name("Anker 747 Charger")
                        .description("140W USB-C charger for laptops and devices")
                        .image("https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400")
                        .category("Accessories")
                        .price(89.99)
                        .quantity(21)
                        .internalReference("ANKER-747")
                        .shellId(33L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.4)
                        .build(),

                Product.builder()
                        .code("CHARGER003")
                        .name("Belkin BoostCharge Pro")
                        .description("108W USB-C charger with GaN technology")
                        .image("https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400")
                        .category("Accessories")
                        .price(79.99)
                        .quantity(26)
                        .internalReference("BELKIN-BCP")
                        .shellId(34L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.5)
                        .build(),

                Product.builder()
                        .code("CABLE002")
                        .name("Lightning to USB-C Cable")
                        .description("2m cable for fast charging Apple devices")
                        .image("https://images.unsplash.com/photo-1591290619762-d71b2e2a4c14?w=400")
                        .category("Accessories")
                        .price(29.99)
                        .quantity(75)
                        .internalReference("CABLE-LIGHT-2M")
                        .shellId(35L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.3)
                        .build(),

                Product.builder()
                        .code("CABLE003")
                        .name("Micro USB Cable Pack")
                        .description("3-pack of 1m Micro USB cables")
                        .image("https://images.unsplash.com/photo-1591290619762-d71b2e2a4c14?w=400")
                        .category("Accessories")
                        .price(14.99)
                        .quantity(120)
                        .internalReference("CABLE-MICRO-3PK")
                        .shellId(36L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.1)
                        .build(),

                Product.builder()
                        .code("SCREEN001")
                        .name("Tempered Glass Screen Protector")
                        .description("Premium screen protector for smartphones")
                        .image("https://images.unsplash.com/photo-1591290619762-d71b2e2a4c14?w=400")
                        .category("Accessories")
                        .price(9.99)
                        .quantity(200)
                        .internalReference("SCREEN-PROT")
                        .shellId(37L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.4)
                        .build(),

                Product.builder()
                        .code("CASE001")
                        .name("OtterBox Defender Series")
                        .description("Rugged protective case for smartphones")
                        .image("https://images.unsplash.com/photo-1591290619762-d71b2e2a4c14?w=400")
                        .category("Accessories")
                        .price(49.99)
                        .quantity(45)
                        .internalReference("OTTERBOX-DEF")
                        .shellId(38L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.6)
                        .build(),

                Product.builder()
                        .code("ADAPTER001")
                        .name("USB-C Hub Adapter")
                        .description("7-in-1 USB-C dock for expanded connectivity")
                        .image("https://images.unsplash.com/photo-1591290619762-d71b2e2a4c14?w=400")
                        .category("Accessories")
                        .price(39.99)
                        .quantity(38)
                        .internalReference("USB-HUB-7IN1")
                        .shellId(39L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.5)
                        .build(),

                Product.builder()
                        .code("STAND001")
                        .name("Adjustable Laptop Stand")
                        .description("Ergonomic aluminum laptop stand")
                        .image("https://images.unsplash.com/photo-1591290619762-d71b2e2a4c14?w=400")
                        .category("Accessories")
                        .price(44.99)
                        .quantity(33)
                        .internalReference("LAPTOP-STAND")
                        .shellId(40L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.7)
                        .build(),

                Product.builder()
                        .code("BAG001")
                        .name("Peak Design Everyday Backpack")
                        .description("Versatile camera and laptop backpack")
                        .image("https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400")
                        .category("Accessories")
                        .price(129.95)
                        .quantity(17)
                        .internalReference("PD-EVERYDAY-BP")
                        .shellId(41L)
                        .inventoryStatus(InventoryStatus.INSTOCK)
                        .rating(4.8)
                        .build());

        productRepository.saveAll(products);
        System.out.println("Database initialized with " + products.size() + " products");
    }
}
